### ISSUE TITLE
webpage seems broken, there is nothing to open a new graph

### ISSUE THREAD

**Issue by DrSpaniel** [antoinechampion/eisenhower-matrix#3]
should it look like this? if so, how do i get the matrix working?
![image](https://github.com/user-attachments/assets/aa83b587-8e4a-4741-9a62-218d9ec9fe54)

**Comment by antoinechampion** [comment]
@DrSpaniel  Do you experience that through eisenhowermatrix.net or your own deployment?

**Comment by antoinechampion** [comment]
Closing as stale
